baseURL = 'https://example.org/'
disableKinds = ['rss','sitemap','taxonomy','term']

printPathWarnings = true

defaultContentLanguage = 'en'

[languages.en]
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1
title = 'Hugo GitHub Issue #13346 (en)'

[languages.de]
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
weight = 2
title = 'Hugo GitHub Issue #13346 (de)'


# EN content
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

# DE content
[[module.mounts]]
source = 'content/de'
target = 'content'
lang = 'de'

#------------------------------------------------------------------------------
# Fill in the missing translations
#------------------------------------------------------------------------------

# This fills in the gaps in DE content with EN content.
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'de'
